name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Cache cargo artifacts
      id: cache-cargo
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.cargo
          ~/extapi-dpm/target/debug/deps
        key: ${{ runner.os }}-test

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run tests
      run: cargo test
