name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Rust toolkit
      run: rustup toolchain install stable --profile minimal


    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "rust"

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run tests
      run: cargo test
